version: "3"
services:
  web:
    container_name: web
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/myportfolio

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

volumes:
  nginx_secrets:
