name: Deploy
 
on:
 push:
   branches:
     - main
 workflow_dispatch:
  
jobs:
 deploy:
   name: "Deploying to AWS EC2 Virtual Machine"
   runs-on: ubuntu-latest
   steps:
     - name: Configuring SSH
       run: |
         mkdir -p ~/.ssh/
         echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
         chmod 600 ~/.ssh/deploy-key.pem
         cat >>~/.ssh/config << END
         Host my-vm
           HostName $SSH_IP
           User $SSH_USER
           IdentityFile ~/.ssh/deploy-key.pem
           StrictHostKeyChecking no
         END
       env:
         SSH_USER: ${{ secrets.SSH_USER }}
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         SSH_IP: ${{ secrets.SSH_IP }}
    
     - name: Deploying Site
       run: ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && git fetch && git reset --hard origin/main && COMPOSE_HTTP_TIMEOUT=300 docker-compose down && COMPOSE_HTTP_TIMEOUT=300 docker-compose up -d --build'
      
     - name: Checking out files
       uses: actions/checkout@v2

     - name: Testing Endpoints
       run: sleep 5 && ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && bash test-endpoints.sh'

     - name: Checking out files
       uses: actions/checkout@v2